APP_CONFIG_ANY_PROVIDER = -1

APP_CONFIG_SCRAPPER_JOB_ENABLED_PREFIX = 'scrapper_job_enabled'

APP_CONFIG_SCRAPPER_JOB_PROVIDER_ENABLED = 'scrapper_job_provider_enabled'
APP_CONFIG_SCRAPPER_JOB_DATA_TARGET_PARALLELISM = 'scrapper_job_data_target_parallelism'

APP_CONFIG_SCRAPPER_IGNORED_CHANNELS = 'scrapper_ignored_channels'
APP_CONFIG_SCRAPPER_SUPPRESSED_TITLE_WORDS = 'scrapper_suppressed_title_words'

VIDEO_STATUS_ID_UNAPPROVED = 1
VIDEO_STATUS_ID_APPROVED = 2
VIDEO_STATUS_ID_IGNORED = 3
VIDEO_STATUS_ID_UPLOADED = 4
VIDEO_STATUS_ID_SUPPRESSED = 5

PROVIDER_ID_TIKTOK = 2

TARGET_TYPE_ID_CHANNEL = 2

DEFAULT_TARGET_RATING = 0