JOB_TYPE_ROOT = 'scrapper_root'
JOB_TYPE_TARGETS_LIST = 'scrapper_targets_list'
JOB_TYPE_PUBLISH_VIDEOS = 'publish_videos'

JOB_STATUS_STARTED = 'started'
JOB_STATUS_FINISHED = 'finished'

FINISH_CODE_OK = 'OK'
FINISH_CODE_FAIL = 'FAIL'

#DRIVER_FILE = 'geckodriver.exe'
DRIVER_FILE = 'geckodriver'

SCRAPPER_SCRIPT_RUN_TYPE_UPDATES = 'SCRAPPER_SCRIPT_RUN_TYPE_UPDATES'
SCRAPPER_SCRIPT_RUN_TYPE_FULL = 'SCRAPPER_SCRIPT_RUN_TYPE_FULL'

VIDEO_PREVIEW_DIR_NAME = 'video_preview'

SCRAPPER_REQUEST_TIMEOUT_SEC = 120
